const DATA_URL = '../data/full_exercises.json';
const CONFIG_URL = '../config/site.json';
const STORAGE_KEY = 'englishTests.fullWord.progress.v1';
const MIN_BLANK_PERCENTAGE = 5;
const MAX_BLANK_PERCENTAGE = 30;
const DEFAULT_BLANK_PERCENTAGE = 17;
const PUNCTUATION = ".!,?;:'\"()[]{}<>—";
const BLANK_SELECTION_BIAS_RULES = [
  { words: new Set(['and', 'but', 'or', 'so', 'because', 'it', 'also']), weight: 5 },
  { words: new Set(['as', 'when', 'before', 'after', 'afterwards', 'firstly', 'then', 'finally', 'although', 'though', 'even', 'if', 'unless', 'while', 'whereas', 'since', 'until']), weight: 2 }
];
let exercises = [];
let currentIndex = 0;
let currentExercise = null;
let currentState = null;
let progress = {};
let toolbar = null;
let features = {};
let requestedGapCount = null;
const get = (id) => document.getElementById(id);

function readProgress() { try { return JSON.parse(localStorage.getItem(STORAGE_KEY) || '{}'); } catch (error) { return {}; } }
function writeProgress() { try { localStorage.setItem(STORAGE_KEY, JSON.stringify(progress)); } catch (error) { /* optional */ } }
function shuffle(items) { const copy = [...items]; for (let i = copy.length - 1; i > 0; i--) { const j = Math.floor(Math.random() * (i + 1)); [copy[i], copy[j]] = [copy[j], copy[i]]; } return copy; }
function parseToken(token) { let leading = ''; let trailing = ''; let core = token; while (core && PUNCTUATION.includes(core[0])) { leading += core[0]; core = core.slice(1); } while (core && PUNCTUATION.includes(core[core.length - 1])) { trailing = core[core.length - 1] + trailing; core = core.slice(0, -1); } return { leading, core, trailing }; }
function weightedPool(words) { return words.map((word, index) => { const parsed = parseToken(word); const rule = BLANK_SELECTION_BIAS_RULES.find((candidate) => candidate.words.has(parsed.core.toLowerCase())); return { word, core: parsed.core, index, weight: rule ? rule.weight : 1 }; }).filter((entry) => entry.core); }
function pickWeighted(pool) { const total = pool.reduce((sum, entry) => sum + entry.weight, 0); let threshold = Math.random() * total; for (let i = 0; i < pool.length; i++) { threshold -= pool[i].weight; if (threshold <= 0) return i; } return pool.length - 1; }
function selectBlanks(pool, count, minimumDistance) { const selected = {}; const remaining = pool.map((entry) => ({ ...entry })); while (Object.keys(selected).length < Math.min(count, pool.length) && remaining.length) { const candidate = remaining.splice(pickWeighted(remaining), 1)[0]; if (Object.keys(selected).every((index) => Math.abs(Number(index) - candidate.index) >= minimumDistance)) selected[candidate.index] = candidate.core.toLowerCase(); } pool.filter((entry) => !selected[entry.index]).slice(0, count - Object.keys(selected).length).forEach((entry) => { selected[entry.index] = entry.core.toLowerCase(); }); return selected; }
function createFullExercise(text, percentage, includeExtras, extraMultiplier, gapCount = null) {
  const words = text.match(/\S+/g) || []; const pool = weightedPool(words); const count = pool.length ? Math.min(pool.length, gapCount ?? Math.max(1, Math.floor(pool.length * percentage / 100))) : 0; const blanks = selectBlanks(pool, count, 3); const displayParts = words.map((word, index) => blanks[index] ? parseToken(word).leading + '<BLANK_' + index + '>' + parseToken(word).trailing : word); let wordBank = Object.values(blanks);
  if (includeExtras) wordBank = wordBank.concat(words.filter((word, index) => !blanks[index]).slice(0, Math.ceil(wordBank.length * extraMultiplier)).map((word) => parseToken(word).core.toLowerCase()));
  return { displayParts, blanks, wordBank: shuffle(wordBank) };
}
function blankSettings() { const percentage = Number(get('blankSlider').value); const extras = get('includeRandomWords').checked; return { percentage, extras, multiplier: extras ? Number(get('extraWordsSlider').value) : 0, gapCount: requestedGapCount }; }
function chooseIndex(exclude = -1) { const options = exercises.map((exercise, index) => index).filter((index) => index !== exclude); return options[Math.floor(Math.random() * options.length)]; }
function renderParts(container, parts, blanks, resultMap = null) { container.replaceChildren(); parts.forEach((part) => { const match = part.match(/^(.*)<BLANK_(\d+)>(.*)$/); if (!match) { container.append(document.createTextNode(part + ' ')); return; } container.append(document.createTextNode(match[1])); const index = Number(match[2]); const span = document.createElement('span'); const result = resultMap ? resultMap[index] : null; if (result) { span.className = result.state.toLowerCase(); span.textContent = result.state === 'Correct' ? result.user : result.state === 'Unanswered' ? 'No answer' : result.user + ' (Correct: ' + result.correct + ')'; } else { const input = document.createElement('input'); input.type = 'text'; input.name = 'blank_' + index; input.className = 'blank-input'; input.setAttribute('aria-label', 'Answer for gap ' + (index + 1)); input.autocomplete = 'off'; input.style.width = Math.min(224, Math.max(80, (blanks[index] || '').length * 9 + 42)) + 'px'; span.appendChild(input); } container.append(span, document.createTextNode(match[3] + ' ')); }); }
function renderAttempt(index, announce = true) { if (index !== currentIndex) requestedGapCount = null; currentIndex = index; currentExercise = exercises[index]; const settings = blankSettings(); const generated = createFullExercise(currentExercise.text, settings.percentage, settings.extras, settings.multiplier, settings.gapCount); requestedGapCount = Object.keys(generated.blanks).length; currentState = { ...generated, originalText: currentExercise.text, title: currentExercise.title }; get('exerciseTitle').textContent = currentExercise.title; get('exerciseProgress').textContent = currentExercise.title + ' · ' + Object.keys(generated.blanks).length + ' gaps · ' + (currentExercise.text.match(/\S+/g) || []).length + ' words'; get('gapCountValue').textContent = Object.keys(generated.blanks).length + ' gaps'; renderParts(get('exerciseTextContainer'), generated.displayParts, generated.blanks); const stored = progress[String(currentExercise.exerciseId)]; if (stored) get('exerciseProgress').textContent += ' · Last score ' + stored.score + '/' + stored.total; get('wordBankContainer').replaceChildren(); generated.wordBank.forEach((word) => { const item = document.createElement('span'); item.textContent = word; get('wordBankContainer').appendChild(item); }); get('resultsPanel').hidden = true; get('exercisePanel').hidden = false; toolbar?.update(index); if (announce) showStatus('Exercise ready.'); get('exerciseTitle').focus(); }
function renderResults(results, score) { const unanswered = results.filter((result) => result.state === 'Unanswered').length; get('scoreDisplay').textContent = score; get('totalDisplay').textContent = results.length; get('resultsSummary').textContent = score + ' of ' + results.length + ' answers correct.' + (unanswered ? ' ' + unanswered + ' unanswered.' : ''); const map = Object.fromEntries(results.map((result) => [result.index, result])); renderParts(get('resultsContent'), currentState.displayParts, currentState.blanks, map); const original = get('originalTextDisplay'); original.replaceChildren(); currentState.originalText.split(/\s+/).forEach((word, index) => { const value = document.createElement('span'); value.textContent = word + ' '; if (currentState.blanks[index]) value.className = 'correct'; original.appendChild(value); }); get('exercisePanel').hidden = true; get('resultsPanel').hidden = false; get('resultsHeading').focus(); showStatus('Results ready.'); }
function checkAnswers(event) { event.preventDefault(); if (!currentState) return; const results = Object.entries(currentState.blanks).map(([index, correct]) => { const input = get('exerciseForm').elements['blank_' + index]; const user = input.value.trim().toLowerCase(); const unanswered = !user; const isCorrect = !unanswered && user === correct.toLowerCase(); return { index: Number(index), user: user || 'No answer', correct, state: unanswered ? 'Unanswered' : isCorrect ? 'Correct' : 'Incorrect' }; }); const score = results.filter((result) => result.state === 'Correct').length; progress[String(currentExercise.exerciseId)] = { score, total: results.length, at: new Date().toISOString() }; writeProgress(); renderResults(results, score); }
function clearAnswers() { document.querySelectorAll('.blank-input').forEach((input) => { input.value = ''; }); showStatus('Answers cleared.'); }
function showStatus(message, kind = '') { const status = get('status'); status.textContent = message; status.className = 'status' + (kind ? ' status-' + kind : ''); }
function showDemoControls() { get('demoControls').hidden = false; }
function setUpEvents() { get('exerciseForm').addEventListener('submit', checkAnswers); get('clearBlanksBtn').addEventListener('click', clearAnswers); get('getNewTestBtn').addEventListener('click', () => { toolbar?.resetTimer(); renderAttempt(chooseIndex(currentIndex)); }); get('reblankTextBtn').addEventListener('click', () => { toolbar?.resetTimer(); renderAttempt(currentIndex); }); get('includeRandomWords').addEventListener('change', (event) => { get('extraWordsSliderContainer').hidden = !event.target.checked; renderAttempt(currentIndex, false); }); get('blankSlider').addEventListener('input', (event) => { requestedGapCount = null; get('blankSliderValue').textContent = event.target.value + '%'; renderAttempt(currentIndex, false); }); get('decreaseGapsBtn').addEventListener('click', () => { requestedGapCount = Math.max(1, Object.keys(currentState.blanks).length - 1); renderAttempt(currentIndex, false); }); get('increaseGapsBtn').addEventListener('click', () => { const limit = weightedPool(currentExercise.text.match(/\S+/g) || []).length; requestedGapCount = Math.min(limit, Object.keys(currentState.blanks).length + 1); renderAttempt(currentIndex, false); }); }
function changeExercise(index) { if (index === currentIndex) return true; if (!get('exercisePanel').hidden && document.querySelector('.blank-input') && [...document.querySelectorAll('.blank-input')].some((input) => input.value) && !window.confirm('Change exercise and discard the current answers?')) return false; toolbar?.resetTimer(); renderAttempt(index); return true; }
async function initialize() { try { const config = await window.EnglishTestsSiteConfig.load(CONFIG_URL); const configured = window.EnglishTestsSiteConfig.getExercise(config, 'full-word'); if (configured && configured.enabled === false) { showStatus('This exercise is currently unavailable.', 'error'); return; } features = config.loaded === false ? { exerciseSelector: true, progress: true, timer: { enabled: true, mode: 'optional', defaultMinutes: 20 } } : window.EnglishTestsSiteConfig.resolveFeatures(config, 'full-word'); const response = await fetch(DATA_URL); if (!response.ok) throw new Error('HTTP ' + response.status); exercises = await response.json(); if (!Array.isArray(exercises) || !exercises.length) throw new Error('No exercises found'); progress = readProgress(); showDemoControls(); toolbar = window.EnglishTestsToolbar.mount(get('exerciseToolbar'), { exercises, currentIndex: 0, features, onExerciseChange: changeExercise }); setUpEvents(); renderAttempt(chooseIndex()); } catch (error) { console.error(error); showStatus('Exercises could not be loaded. Please try again later.', 'error'); } }
window.addEventListener('DOMContentLoaded', initialize);
