const DATA_URL='../data/exercises.json', CONFIG_URL='../config/site.json', STORAGE_KEY='englishTests.slider.progress.v1';
let exercises=[], currentIndex=0, currentExercise=null, toolbar=null, currentResults=[];
const get=(id)=>document.getElementById(id);
const shuffle=(items)=>{const result=[...items];for(let i=result.length-1;i>0;i-=1){const j=Math.floor(Math.random()*(i+1));[result[i],result[j]]=[result[j],result[i]];}return result;};
const correctWord=(gap)=>gap.options[gap.correctIndex];
function choiceDensity(){return Number(get('choiceCountSlider').value);}
function renderText(container, exercise, results=null){container.replaceChildren();const map=results&&new Map(results.map((item)=>[item.gapId,item]));exercise.text.split(/(\[GAP_\d+\])/g).forEach((part)=>{const match=part.match(/^\[GAP_(\d+)\]$/);if(!match){container.append(document.createTextNode(part));return;}const id=Number(match[1]),result=map?.get(id);if(result){const output=document.createElement('span');output.className=result.state.toLowerCase();output.textContent=result.state==='Correct'?result.user:result.state==='Unanswered'?'No answer':result.user+' (Correct: '+result.correct+')';container.append(output);return;}const input=document.createElement('input');input.type='text';input.name='gap_'+id;input.className='blank-input';input.autocomplete='off';input.setAttribute('aria-label','Answer for gap '+id);container.append(input);});}
function renderBank(){const bank=get('wordBankContainer');bank.replaceChildren();const all=currentExercise.gaps.flatMap((gap)=>gap.options), count=Math.max(currentExercise.gaps.length,Math.ceil(all.length*choiceDensity()/100));shuffle([...new Set(all)]).slice(0,count).forEach((word)=>{const item=document.createElement('span');item.textContent=word;bank.append(item);});get('wordBankHeading').textContent='Word bank ('+choiceDensity()+'% coverage)';get('choiceCountValue').textContent=choiceDensity()+'%';}
function renderAttempt(index){currentIndex=index;currentExercise=exercises[index];currentResults=[];get('exerciseTitle').textContent=currentExercise.title;get('exerciseProgress').textContent=currentExercise.title+' · '+currentExercise.gaps.length+' gaps · '+(currentExercise.text.match(/\S+/g)||[]).length+' words';renderText(get('exerciseTextContainer'),currentExercise);renderBank();get('exercisePanel').hidden=false;get('resultsPanel').hidden=true;toolbar?.update(index);get('exerciseTitle').focus();get('status').textContent='Exercise ready.';}
function saveResult(score){let saved={};try{saved=JSON.parse(localStorage.getItem(STORAGE_KEY))||{};}catch{}saved[String(currentExercise.exerciseId)]={score,total:currentExercise.gaps.length,at:new Date().toISOString()};localStorage.setItem(STORAGE_KEY,JSON.stringify(saved));}
function showResults(results,score){const unanswered=results.filter((item)=>item.state==='Unanswered').length;get('scoreDisplay').textContent=score;get('totalDisplay').textContent=currentExercise.gaps.length;get('resultsSummary').textContent=score+' of '+currentExercise.gaps.length+' answers correct.'+(unanswered?' '+unanswered+' unanswered.':'');renderText(get('resultsContent'),currentExercise,results);const original=get('originalTextDisplay');renderText(original,{...currentExercise,text:currentExercise.text},results.map((item)=>({...item,state:'Correct',user:item.correct})));const list=get('feedbackList');list.replaceChildren();results.forEach((result)=>{const item=document.createElement('div');item.className='feedback-item';const heading=document.createElement('strong');heading.textContent='Gap '+result.gapId+': '+result.state;const user=document.createElement('p');user.textContent="User's answer: "+result.user;const answer=document.createElement('p');answer.textContent='Correct answer: '+result.correct;const focus=document.createElement('p');focus.textContent='Focus: '+result.focus;const explanation=document.createElement('p');explanation.textContent=result.explanation;item.append(heading,user,answer,focus,explanation);list.append(item);});get('exercisePanel').hidden=true;get('resultsPanel').hidden=false;get('resultsHeading').focus();get('status').textContent='Results ready.';}
function checkAnswers(event){event.preventDefault();const results=currentExercise.gaps.map((gap)=>{const input=get('exerciseForm').elements['gap_'+gap.id],user=input.value.trim(),correct=correctWord(gap);return{gapId:gap.id,user:user||'No answer',correct,state:!user?'Unanswered':user.toLowerCase()===correct.toLowerCase()?'Correct':'Incorrect',focus:gap.focus,explanation:gap.explanation};});const score=results.filter((item)=>item.state==='Correct').length;currentResults=results;saveResult(score);showResults(results,score);}
function nextExercise(){toolbar?.resetTimer();const next=(currentIndex+1+Math.floor(Math.random()*Math.max(1,exercises.length-1)))%exercises.length;renderAttempt(next);}
function changeExercise(index){if(index===currentIndex)return true;const hasAnswers=[...document.querySelectorAll('.blank-input')].some((input)=>input.value.trim());if(hasAnswers&&!window.confirm('Change exercise and discard the current answers?'))return false;toolbar?.resetTimer();renderAttempt(index);return true;}
function initializeEvents(){get('exerciseForm').addEventListener('submit',checkAnswers);get('clearBlanksBtn').addEventListener('click',()=>{document.querySelectorAll('.blank-input').forEach((input)=>input.value='');get('status').textContent='Answers cleared.';});get('getNewTestBtn').addEventListener('click',nextExercise);get('backToExerciseBtn').addEventListener('click',nextExercise);get('choiceCountSlider').addEventListener('input',renderBank);}
async function initialize(){try{const config=await window.EnglishTestsSiteConfig.load(CONFIG_URL),settings=config.loaded===false?{exerciseSelector:true,progress:true,timer:{enabled:true,mode:'optional',defaultMinutes:20}}:window.EnglishTestsSiteConfig.resolveFeatures(config,'slider');if(window.EnglishTestsSiteConfig.getExercise(config,'slider')?.enabled===false)return;const response=await fetch(DATA_URL);if(!response.ok)throw new Error('HTTP '+response.status);exercises=await response.json();if(!Array.isArray(exercises)||!exercises.length)throw new Error('No exercises found');toolbar=window.EnglishTestsToolbar.mount(get('exerciseToolbar'),{exercises,currentIndex:0,features:settings,onExerciseChange:changeExercise});initializeEvents();renderAttempt(Math.floor(Math.random()*exercises.length));}catch(error){console.error(error);get('status').textContent='Exercises could not be loaded. Please try again later.';}}
window.addEventListener('DOMContentLoaded',initialize);
