const DATA_URL = '../data/partial_exercises.json';
const CONFIG_URL = '../config/site.json';
const STORAGE_KEY = 'englishTests.partialWord.progress.v1';
const PUNCTUATION = ".!,?;:'\"()[]{}<>—";
const MIN_DISTANCE = 3;
let exercises = [], currentIndex = 0, currentExercise = null, currentState = null, progress = {}, toolbar = null;

const get = (id) => document.getElementById(id);
const shuffle = (items) => { const result = [...items]; for (let i = result.length - 1; i > 0; i -= 1) { const j = Math.floor(Math.random() * (i + 1)); [result[i], result[j]] = [result[j], result[i]]; } return result; };
function parseToken(token) { let core = token, leading = '', trailing = ''; while (core && PUNCTUATION.includes(core[0])) leading += core[0], core = core.slice(1); while (core && PUNCTUATION.includes(core.at(-1))) trailing = core.at(-1) + trailing, core = core.slice(0, -1); return { core, leading, trailing }; }
function words(text) { return text.match(/\S+/g) || []; }
function selectBlanks(tokens, percentage) { const eligible = tokens.map((word, index) => ({ word, index, core: parseToken(word).core })).filter((item) => item.core.length > 0); const count = Math.max(1, Math.floor(eligible.length * percentage / 100)); const chosen = {}; const pool = shuffle(eligible); pool.forEach((candidate) => { if (Object.keys(chosen).length >= count || Object.keys(chosen).some((index) => Math.abs(Number(index) - candidate.index) < MIN_DISTANCE)) return; chosen[candidate.index] = candidate; }); pool.forEach((candidate) => { if (Object.keys(chosen).length < count && !chosen[candidate.index]) chosen[candidate.index] = candidate; }); return chosen; }
function createPartial(text, percentage, extras, multiplier) { const tokens = words(text), selected = selectBlanks(tokens, percentage), blanks = {}, parts = tokens.map((token) => token); Object.entries(selected).forEach(([index, item]) => { if (item.core.length <= 4) return; const count = Math.max(2, Math.min(6, Math.floor(item.core.length * (.3 + Math.random() * .1)))); const start = Math.random() < .5 ? 0 : item.core.length - count; const missing = item.core.slice(start, start + count).toLowerCase(); const parsed = parseToken(item.word); blanks[index] = missing; parts[index] = parsed.leading + parsed.core.slice(0, start) + '<BLANK_' + index + '>' + parsed.core.slice(start + count) + parsed.trailing; }); let bank = Object.values(blanks); if (extras) { const additional = tokens.filter((token, index) => !blanks[index]).map((token) => parseToken(token).core).filter((word) => word.length > 4).slice(0, Math.ceil(bank.length * multiplier)).map((word) => { const length = Math.max(1, Math.min(6, Math.floor(word.length * .9))); const start = Math.floor(Math.random() * Math.max(1, word.length - length)); return word.slice(start, start + length).toLowerCase(); }); bank = bank.concat(additional); } return { blanks, parts, wordBank: shuffle(bank) }; }
function renderText(container, parts, blanks, resultMap) { container.replaceChildren(); parts.forEach((part) => { const match = part.match(/^(.*)<BLANK_(\d+)>(.*)$/); if (!match) { container.append(document.createTextNode(part + ' ')); return; } container.append(document.createTextNode(match[1])); const result = resultMap && resultMap[Number(match[2])]; if (result) { const output = document.createElement('span'); output.className = result.state.toLowerCase(); output.textContent = result.state === 'Correct' ? result.user : result.state === 'Unanswered' ? 'No answer' : result.user + ' (Correct: ' + result.correct + ')'; container.append(output); } else { const input = document.createElement('input'); input.type = 'text'; input.name = 'blank_' + match[2]; input.className = 'blank-input'; input.autocomplete = 'off'; input.setAttribute('aria-label', 'Answer for gap ' + (Number(match[2]) + 1)); input.style.width = Math.min(224, Math.max(80, (blanks[Number(match[2])] || '').length * 12 + 42)) + 'px'; container.append(input); } container.append(document.createTextNode(match[3] + ' ')); }); }
function readProgress() { try { return JSON.parse(localStorage.getItem(STORAGE_KEY)) || {}; } catch { return {}; } }
function saveProgress() { localStorage.setItem(STORAGE_KEY, JSON.stringify(progress)); }
function showStatus(message, kind = '') { get('status').textContent = message; get('status').className = 'status' + (kind ? ' status-' + kind : ''); }
function settings() { const extras = get('includeRandomWords').checked; return { percentage: Number(get('blankSlider').value), extras, multiplier: extras ? Number(get('extraWordsSlider').value) : 0 }; }
function renderAttempt(index, announce = true) { currentIndex = index; currentExercise = exercises[index]; const generated = createPartial(currentExercise.text, ...Object.values(settings())); currentState = { ...generated, originalText: currentExercise.text }; get('exerciseTitle').textContent = currentExercise.title; get('exerciseProgress').textContent = currentExercise.title + ' · ' + Object.keys(generated.blanks).length + ' gaps'; renderText(get('exerciseTextContainer'), generated.parts, generated.blanks); get('wordBankContainer').replaceChildren(...generated.wordBank.map((word) => { const item = document.createElement('span'); item.textContent = word; return item; })); get('resultsPanel').hidden = true; get('exercisePanel').hidden = false; toolbar?.update(index); if (announce) showStatus('Exercise ready.'); get('exerciseTitle').focus(); }
function renderResults(results, score) { const unanswered = results.filter((result) => result.state === 'Unanswered').length; get('scoreDisplay').textContent = score; get('totalDisplay').textContent = results.length; get('resultsSummary').textContent = score + ' of ' + results.length + ' answers correct.' + (unanswered ? ' ' + unanswered + ' unanswered.' : ''); const map = Object.fromEntries(results.map((result) => [result.index, result])); renderText(get('resultsContent'), currentState.parts, currentState.blanks, map); const original = get('originalTextDisplay'); original.replaceChildren(); currentState.originalText.split(/(\s+)/).forEach((part) => { const node = document.createTextNode(part); original.append(node); }); get('exercisePanel').hidden = true; get('resultsPanel').hidden = false; get('resultsHeading').focus(); showStatus('Results ready.'); }
function checkAnswers(event) { event.preventDefault(); const results = Object.entries(currentState.blanks).map(([index, correct]) => { const input = get('exerciseForm').elements['blank_' + index]; const user = input.value.trim(); const answered = Boolean(user); return { index: Number(index), user: user || 'No answer', correct, state: !answered ? 'Unanswered' : user.toLowerCase() === correct.toLowerCase() ? 'Correct' : 'Incorrect' }; }); const score = results.filter((result) => result.state === 'Correct').length; progress[String(currentExercise.exerciseId)] = { score, total: results.length, at: new Date().toISOString() }; saveProgress(); renderResults(results, score); }
function clearAnswers() { document.querySelectorAll('.blank-input').forEach((input) => { input.value = ''; }); showStatus('Answers cleared.'); }
function changeExercise(index) { if (index === currentIndex) return true; const hasAnswers = [...document.querySelectorAll('.blank-input')].some((input) => input.value.trim()); if (hasAnswers && !window.confirm('Change exercise and discard the current answers?')) return false; toolbar?.resetTimer(); renderAttempt(index); return true; }
function setUpEvents() { get('exerciseForm').addEventListener('submit', checkAnswers); get('clearBlanksBtn').addEventListener('click', clearAnswers); get('getNewTestBtn').addEventListener('click', () => { toolbar?.resetTimer(); renderAttempt((currentIndex + 1 + Math.floor(Math.random() * (exercises.length - 1))) % exercises.length); }); get('reblankTextBtn').addEventListener('click', () => { toolbar?.resetTimer(); renderAttempt(currentIndex); }); get('backToExerciseBtn').addEventListener('click', () => { toolbar?.resetTimer(); renderAttempt((currentIndex + 1 + Math.floor(Math.random() * (exercises.length - 1))) % exercises.length); }); get('includeRandomWords').addEventListener('change', (event) => { get('extraWordsSliderContainer').hidden = !event.target.checked; }); get('blankSlider').addEventListener('input', (event) => { get('blankSliderValue').textContent = event.target.value + '%'; }); }
async function initialize() { try { const config = await window.EnglishTestsSiteConfig.load(CONFIG_URL); const configured = window.EnglishTestsSiteConfig.getExercise(config, 'partial-word'); if (configured?.enabled === false) return showStatus('This exercise is currently unavailable.', 'error'); const features = config.loaded === false ? { exerciseSelector: true, progress: true, timer: { enabled: true, mode: 'optional', defaultMinutes: 20 } } : window.EnglishTestsSiteConfig.resolveFeatures(config, 'partial-word'); const response = await fetch(DATA_URL); if (!response.ok) throw new Error('HTTP ' + response.status); exercises = await response.json(); if (!Array.isArray(exercises) || !exercises.length) throw new Error('No exercises found'); progress = readProgress(); get('demoControls').hidden = new URLSearchParams(window.location.search).get('mode') !== 'demo'; toolbar = window.EnglishTestsToolbar.mount(get('exerciseToolbar'), { exercises, currentIndex: 0, features, onExerciseChange: changeExercise }); setUpEvents(); renderAttempt(Math.floor(Math.random() * exercises.length)); } catch (error) { console.error(error); showStatus('Exercises could not be loaded. Please try again later.', 'error'); } }
window.addEventListener('DOMContentLoaded', initialize);
